=== building-envelope-data/api/schemas/method.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://www.buildingenvelopedata.org/schemas/v1/method.json",
  "title": "method data",
  "description": "Definition of a method that can be applied by a creator to some source data to create a data set. By defining the method and the source data, the origin of the data set can be traced back.",
  "$defs": {
    "method": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "identifier.json#/$defs/central",
          "description": "This id represents the method which is specified below."
        },
        "name": {
          "type": "string",
          "description": "The name of the method."
        },
        "description": {
          "type": "string",
          "description": "Here the method can be described in free text."
        },
        "categories": {
          "title": "With this array, it is defined whether the method is a measurement or a calculation only or both.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["calculation", "measurement"]
          },
          "uniqueItems": true,
          "minItems": 1
        },
        "developer": {
          "$ref": "stakeholder.json",
          "description": "Who developed the method."
        },
        "reference": {
          "$ref": "common.json#/$defs/reference",
          "description": "If the method is an implementation of a standard or of a procedure described in a publication, this reference can be defined here."
        },
        "additionalReferences": {
          "type": "array",
          "items": {
            "$ref": "common.json#/$defs/reference",
            "description": "Additional references that supplement the one given in the property `reference`, like tutorials or manuals as supplements to a formal specification."
          },
          "uniqueItems": true,
          "minItems": 1
        },
        "createdAt": {
          "$ref": "common.json#/$defs/timestamp",
          "description": "When the method was created."
        },
        "validity": {
          "$ref": "common.json#/$defs/openEndedDateTimeRange",
          "description": "Here you can define since when the method is valid and until when. This can be helpful for example when a regulation or standard changes."
        },
        "available": {
          "$ref": "common.json#/$defs/available",
          "description": "Here you can define since when the method has been available and until when. This can be helpful for example when a method is shared considerably later than when it was created. You can also use it to define that the method may have been available for a long time even though it may not be valid for the whole time of its availability."
        },
        "calculation": {
          "$ref": "#/$defs/calculation",
          "description": "Here you can define the calculation procedure in detail."
        },
        "service": {
          "title": "If the method is available as a service, the endpoint and the API specification are defined here.",
          "type": "object",
          "properties": {
            "endpoint": {
              "$ref": "common.json#/$defs/webAddress",
              "description": "The web address of the endpoint to which input data can be send and which returns output data according to the method."
            },
            "specification": {
              "$ref": "common.json#/$defs/webAddress",
              "description": "The web address of the API specification which describes how to send input data and receive output data which was processed by the method."
            }
          },
          "additionalProperties": false,
          "required": ["endpoint"],
          "minProperties": 1
        }
      },
      "additionalProperties": false,
      "required": ["id"]
    },
    "calculation": {
      "title": "A web address which defines the calculation procedure in detail.",
      "$ref": "common.json#/$defs/webAddress",
      "description": "If the calculation procedure is open, the web address should refer to the repository for example at github.com. If the calculation procedure is closed, the web address should provide an explanation of procedure and may describe options to download executables."
    },
    "appliedMethod": {
      "title": "Applied method, that is the application of a method with fixed arguments to specific source data.",
      "type": "object",
      "properties": {
        "method": {
          "$ref": "#/$defs/method",
          "description": "Method that was applied by the creator on the source data."
        },
        "arguments": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/namedArgument",
            "description": "Named arguments to configure the method."
          }
        },
        "sources": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/namedSource",
            "description": "Named data sources to which the method was applied."
          }
        }
      },
      "additionalProperties": false,
      "required": ["method", "arguments", "sources"]
    },
    "namedArgument": {
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "value": {
          "title": "Value of any type"
        }
      },
      "additionalProperties": false,
      "required": ["name", "value"]
    },
    "namedSource": {
      "title": "Source data which is an input for a method. A creator uses a method and source data to create a new data set.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        },
        "value": {
          "title": "Value",
          "$ref": "#/$defs/dataReference"
        }
      },
      "additionalProperties": false,
      "required": ["name", "value"]
    },
    "dataReference": {
      "title": "Data reference",
      "type": "object",
      "properties": {
        "dataId": {
          "$ref": "identifier.json#/$defs/decentral"
        },
        "dataTimestamp": {
          "$ref": "common.json#/$defs/timestamp"
        },
        "dataKind": {
          "description": "Data kind, either calorimetric, hygrothermal, optical, or photovoltaic.",
          "type": "string",
          "enum": [
            "calorimetricData",
            "hygrothermalData",
            "opticalData",
            "photovoltaicData"
          ]
        }
      },
      "additionalProperties": false,
      "required": ["dataId", "dataTimestamp", "dataKind"]
    },
    "database": {
      "description": "Information about a database which has implemented the same API specification.",
      "type": "object",
      "properties": {
        "webAddress": {
          "$ref": "common.json#/$defs/webAddress",
          "description": "The database is identified by its API endpoint."
        },
        "name": {
          "type": "string",
          "description": "The name of the database"
        },
        "description": {
          "type": "string",
          "description": "A description of the database"
        },
        "owner": {
          "$ref": "stakeholder.json#/$defs/institution",
          "description": "The institution which owns the database"
        },
        "admin": {
          "$ref": "stakeholder.json#/$defs/institution",
          "description": "The institution which administrates the database"
        },
        "createdAt": {
          "$ref": "common.json#/$defs/timestamp",
          "description": "When the database was created"
        },
        "validity": {
          "$ref": "common.json#/$defs/openEndedDateTimeRange",
          "description": "For which timespan the data of the database is valid"
        },
        "available": {
          "$ref": "common.json#/$defs/available",
          "description": "For which timespan the database is or was available"
        },
        "internalComment": {
          "type": "string",
          "description": "If there are any specific issues with a database, the administrators can use this string."
        }
      },
      "additionalProperties": false,
      "required": ["webAddress"]
    }
  },
  "$ref": "#/$defs/method"
}

=== building-envelope-data/api/tests/valid/method/method.json
{
  "id": "bcba3ff9-8cb7-4524-943a-786d301d39ef",
  "name": "Method to calculate derived measurement values",
  "description": "dummy",
  "categories": ["calculation"],
  "developer": {
    "id": "bcba3ff9-8cb7-4524-943a-786d301d39e2"
  },
  "createdAt": "2007-03-13T20:20:39+00:00",
  "validity": {
    "from": "2007-03-13T20:20:39+00:00",
    "until": "2008-03-13T20:20:39+00:00"
  },
  "available": {
    "from": "2007-03-13T20:20:39+00:00",
    "until": "2008-03-13T20:20:39+00:00"
  }
}

=== building-envelope-data/api/tests/valid/method/methodThreePhase.json
{
  "id": "473a2f69-2e18-4745-809d-519882b25e8b",
  "name": "Three-phase method",
  "description": "Simulates the daylight performance of complex fenestration systems using a matrix formalism and Bidirectional Scattering Distribution Functions",
  "categories": ["calculation"],
  "calculation": "https://www.radiance-online.org/learning/tutorials/matrix-based-methods",
  "reference": {
    "publication": {
      "identifiers": {
        "doi": "10.1080/15502724.2011.10732150"
      },
      "title": "Simulating the Daylight Performance of Complex Fenestration Systems Using Bidirectional Scattering Distribution Functions within Radiance",
      "abstract": "We describe two methods which rely on bidirectional scattering distribution functions (BSDFs) to model the daylighting performance of complex fenestration systems (CFS), enabling greater flexibility and accuracy in evaluating arbitrary assemblies of glazing, shading, and other optically-complex coplanar window systems. Two tools within Radiance enable a) efficient annual performance evaluations of CFS, and b) accurate renderings of CFS despite the loss of spatial resolution associated with low-resolution BSDF datasets for inhomogeneous systems. Validation, accuracy, and limitations of the methods are discussed."
    }
  },
  "additionalReferences": [
    {
      "standard": {
        "id": "473a2f69-2e18-4745-809d-5a5aafa2ffaf",
        "title": "Calculation of the impact of daylight utilization on the net and final energy demand for lighting",
        "standardizers": ["ISO"],
        "numeration": {
          "mainNumber": 10916
        },
        "year": 2021
      }
    }
  ]
}

=== building-envelope-data/api/tests/valid/method/methodTraceGlare.json
{
  "id": "473a2f69-2e18-4745-809d-519882b25e8b",
  "name": "Dynamic glare risk assessment",
  "description": "Script to run dynamic glare simulations (DGP) by using Radiance raytracing",
  "categories": ["calculation"],
  "calculation": "https://github.com/bbuenoun/trace-glare",
  "reference": {
    "publication": {
      "identifiers": {
        "webAddress": "https://github.com/bbuenoun/trace-glare"
      },
      "title": "Easy-to-Implement Simulation Strategies for Dynamic Glare Risk Assessments based on the European Daylighting Standard",
      "abstract": "This study presents a workflow that can be easily implemented in building simulation programs in order to perform dynamic glare risk assessments based on the DGP method. The DGP method has been used in the preparation of the European Daylighting Standard EN 17037 to recommend glare protection classes of shading devices for different situations (climate, façade orientation, window size, view position and direction). By implementing the DGP method, building simulation programs can be used to make design decisions on conflicting functionality, including glare protection. The DGP method requires detailed information about the optical behaviour of fenestration systems. Measurement procedures that are required to obtain the necessary optical information for glare protection fabrics are described here. The study also points out at new databases that offer accessibility and reliability of optical information for simulation software. A case study is presented to illustrate the proposed workflow. ",
      "authors": [
        { "fullName": "Bruno Bueno" },
        { "fullName": "Abel Sepúlveda" },
        {
          "id": "2c103b27-eb15-423a-a184-fdd6c64eefe2",
          "fullName": "Christoph Maurer"
        },
        {
          "id": "3df7bd32-1517-40b2-a380-9bfa5a34bf66",
          "fullName": "Simon Wacker"
        },
        { "fullName": "Helen Rose Wilson" }
      ]
    }
  }
}
